name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SachiLak2001
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
